### ISSUE TITLE
predictionsByStop's TopCount does not work 

### ISSUE THREAD

**Issue by theaccordance** [projectweekend/Node-CTA-Bus-Tracker#1]
I assume the TopCount is to limit the number of responses?  Anyways, it doesn't work.  Looking at the code for the method, I wasn't even seeing where it's being referenced aside from the local variable declaration.

**Comment by projectweekend** [comment]
Thanks for opening this issue. Good catch. I totally missed that. I will get a fix in as soon as possible.

**Comment by projectweekend** [comment]
Just published a fix. Let me know if you have any issues.
